version: 0.0
os: linux
files:
  - source: blogbackend.jar
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
