version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y wget gnupg
      - wget -O- https://apt.corretto.aws/corretto.key | gpg --dearmor | tee /usr/share/keyrings/corretto-keyring.gpg
      - echo 'deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main' | tee /etc/apt/sources.list.d/corretto.list
      - apt-get update
      # Try using OpenJDK 17 instead of Amazon Corretto
      - apt-get install -y openjdk-17-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Building the Spring Boot application...
      - ./mvnw clean package -DskipTests
      - echo Copying the JAR file to output location...
      - cp target/blogbackend-0.0.1-SNAPSHOT.jar blogbackend.jar
  post_build:
    commands:
      - echo Build completed, preparing artifact...
      - mkdir -p /tmp/deployment
      - cp blogbackend.jar /tmp/deployment/

artifacts:
  files:
    - blogbackend.jar
  discard-paths: yes
  base-directory: .
