version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y wget gnupg
      - wget -O- https://apt.corretto.aws/corretto.key | gpg --dearmor | sudo tee /usr/share/keyrings/corretto-keyring.gpg
      - echo 'deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main' | sudo tee /etc/apt/sources.list.d/corretto.list
      - apt-get update
      - apt-get install -y java-17-amazon-corretto
  pre_build:
    commands:
      - echo Preparing for the build...
  build:
    commands:
      - echo Building the application...
      - ./mvnw clean package -DskipTests
      - echo Copying the JAR file to output location...
      - cp target/blogbackend-0.0.1-SNAPSHOT.jar blogbackend.jar
  post_build:
    commands:
      - echo Build completed successfully...
      - mkdir -p /tmp/deployment
      - cp blogbackend.jar /tmp/deployment/

artifacts:
  files:
    - blogbackend.jar
  discard-paths: yes
  base-directory: .
