version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y openjdk-17-jdk
      - apt-get install -y maven
      - chmod +x ./mvnw
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Building the Spring Boot application...
      - java -version
      - mvn -version
      - ./mvnw clean package -DskipTests
      - echo Copying the JAR file to output location...
      - cp target/blogbackend-0.0.1-SNAPSHOT.jar blogbackend.jar
      - echo Build completed!

  post_build:
    commands:
      - echo Build completed, preparing artifact...
      - mkdir -p /tmp/deployment
      - cp blogbackend.jar /tmp/deployment/

artifacts:
  files:
    - target/blogbackend.jar
  discard-paths: yes
  base-directory: .

